package com.ghostchu.quickshop;

import com.ghostchu.quickshop.util.logger.Log;
import lombok.Data;
import lombok.SneakyThrows;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

import java.io.InputStream;
import java.util.Objects;
import java.util.Properties;

/**
 * BuildInfo is utilities to help read BUILDINFO file that generated by CodeMC Jenkins.
 *
 * @author Ghost_chu
 */
@Data
@NullMarked
public class BuildInfo {

  private final GitInfo gitInfo;
  private final JenkinsInfo ciInfo;

  @SneakyThrows
  public BuildInfo(@Nullable final InputStream inputStream) {
    // Read InputStream to String as UTF-8 encoding with Reader
    if(inputStream == null) {
      gitInfo = new GitInfo(new Properties());
      ciInfo = new JenkinsInfo(new Properties());
      return;
    }
    final Properties properties = new Properties();
    properties.load(inputStream);
    this.gitInfo = new GitInfo(properties);
    this.ciInfo = new JenkinsInfo(properties);
  }

  public static class GitInfo {

    private static final String DEFAULT_VALUE = "undefined";
    private final @Nullable String branch;
    private final boolean dirty;
    private final @Nullable String remoteOriginUrl;
    private final @Nullable String id;
    private final @Nullable String abbrev;
    private final @Nullable String describe;
    private final @Nullable String describeShort;
    private final @Nullable String commitUsername;
    private final @Nullable String commitEmail;
    private final @Nullable String commitMessage;
    private final @Nullable String commitDate;
    private final @Nullable String buildTime;
    private final @Nullable String buildVersion;
    private final @Nullable String buildNumber;
    private final @Nullable String tags;

    public GitInfo(final Properties properties) {

      this.tags = properties.getProperty("git.tags");
      this.branch = properties.getProperty("git.branch");
      this.dirty = "true".equalsIgnoreCase(properties.getProperty("git.dirty"));
      this.remoteOriginUrl = properties.getProperty("git.remote.origin.url");
      this.id = properties.getProperty("git.commit.id");
      this.abbrev = properties.getProperty("git.commit.id.abbrev");
      this.describe = properties.getProperty("git.commit.id.describe");
      this.describeShort = properties.getProperty("git.commit.id.describe-short");
      this.commitUsername = properties.getProperty("git.commit.user.name");
      this.commitEmail = properties.getProperty("git.commit.user.email");
      this.commitMessage = properties.getProperty("git.commit.message.short");
      this.commitDate = properties.getProperty("git.commit.time");
      this.buildTime = properties.getProperty("git.build.time");
      this.buildVersion = properties.getProperty("git.build.version");
      this.buildNumber = properties.getProperty("git.build.number");
    }

    public String getAbbrev() {

      if(abbrev == null) {
        return DEFAULT_VALUE;
      }
      return abbrev;
    }

    public String getBranch() {

      if(branch == null) {
        return DEFAULT_VALUE;
      }
      return branch;
    }

    public String getBuildNumber() {

      return Objects.requireNonNullElse(buildNumber, DEFAULT_VALUE);
    }

    public String getBuildTime() {

      return Objects.requireNonNullElse(buildTime, DEFAULT_VALUE);
    }

    public String getBuildVersion() {

      return Objects.requireNonNullElse(buildVersion, DEFAULT_VALUE);
    }

    public String getCommitDate() {

      return Objects.requireNonNullElse(commitDate, DEFAULT_VALUE);
    }

    public String getCommitEmail() {

      return Objects.requireNonNullElse(commitEmail, DEFAULT_VALUE);
    }

    public String getCommitMessage() {

      return Objects.requireNonNullElse(commitMessage, DEFAULT_VALUE);
    }

    public String getCommitUsername() {

      return Objects.requireNonNullElse(commitUsername, DEFAULT_VALUE);
    }

    public String getDescribe() {

      return Objects.requireNonNullElse(describe, DEFAULT_VALUE);
    }

    public String getDescribeShort() {

      return Objects.requireNonNullElse(describeShort, DEFAULT_VALUE);
    }

    public String getId() {

      if(id == null) {
        return DEFAULT_VALUE;
      }
      return id;
    }

    public String getRemoteOriginUrl() {

      return Objects.requireNonNullElse(remoteOriginUrl, DEFAULT_VALUE);
    }

    public String getTags() {

      if(tags == null) {
        return DEFAULT_VALUE;
      }
      return tags;
    }

    public boolean isDirty() {

      return dirty;
    }
  }

  public static class JenkinsInfo {

    private static final String DEFAULT_VALUE = "undefined";
    private final boolean ci;
    private final int id;
    private final @Nullable String idName;
    private final @Nullable String tag;
    private final @Nullable String url;
    private final @Nullable String projectName;
    private final @Nullable String projectUrl;
    private final @Nullable String projectBaseName;


    public JenkinsInfo(final Properties properties) {

      this.ci = "true".equalsIgnoreCase(properties.getProperty("jenkins.ci"));
      final String idStr = properties.getProperty("ci.build.id");
      if(idStr != null) {
        int fid = -1;
        try {
          fid = Integer.parseInt(properties.getProperty("ci.build.id"));
        } catch(NumberFormatException ex) {
          Log.debug("Failed to parse fid: " + ex.getMessage());
        } finally {
          this.id = fid;
        }
      } else {
        this.id = -1;
      }
      this.idName = properties.getProperty("ci.build.name");
      this.tag = properties.getProperty("ci.build.tag");
      this.url = properties.getProperty("ci.build.url");
      this.projectName = properties.getProperty("ci.job.name");
      this.projectUrl = properties.getProperty("ci.job.url");
      this.projectBaseName = properties.getProperty("ci.job.base_name");
    }

    public int getId() {

      return id;
    }

    public String getIdName() {

      if(idName == null) {
        return DEFAULT_VALUE;
      }
      return idName;
    }

    public String getProjectBaseName() {

      return Objects.requireNonNullElse(projectBaseName, DEFAULT_VALUE);
    }

    public String getProjectName() {

      return Objects.requireNonNullElse(projectName, DEFAULT_VALUE);
    }

    public String getProjectUrl() {

      return Objects.requireNonNullElse(projectUrl, DEFAULT_VALUE);
    }

    public String getTag() {

      if(tag == null) {
        return DEFAULT_VALUE;
      }
      return tag;
    }

    public String getUrl() {

      if(url == null) {
        return DEFAULT_VALUE;
      }
      return url;
    }

    public boolean isCi() {

      return ci;
    }
  }

}
